/** S8 (QA): подання URL фікстури через справжній UI (web :3000 -> api :3001 -> worker) і доказ по кліку. Використання: tsx scripts/s8-ui-submit.ts <outDir> [url] [uk|en] */
import fs from "node:fs";
import path from "node:path";
import { chromium } from "playwright";

const out = path.resolve(process.argv[2] ?? "planning/qa/artifacts/sprint-8/ui");
const url = process.argv[3] ?? "http://127.0.0.1:4210/";
const BASE = process.env["SL_WEB"] ?? "http://127.0.0.1:3000";
const lang = process.argv[4] ?? "uk";
fs.mkdirSync(out, { recursive: true });
const b = await chromium.launch();
const ctx = await b.newContext({ viewport: { width: 1440, height: 900 } });
await ctx.addCookies([{ name: "sl_lang", value: lang, url: BASE }]);
const page = await ctx.newPage();
const errs: string[] = [];
page.on("pageerror", (e) => errs.push(e.message));
const res: Record<string, unknown> = { url, base: BASE, lang };
await page.goto(`${BASE}/`);
await page.getByTestId("url-input").fill(url);
await page.screenshot({ path: path.join(out, "01-landing-filled.png") });
await page.getByTestId("analyze").click();
await page.getByTestId("progress").waitFor({ timeout: 30_000 });
res["auditUrl"] = page.url();
await page.screenshot({ path: path.join(out, "02-progress.png") });
await page.getByTestId("report").waitFor({ timeout: 8 * 60_000 });
await page.screenshot({ path: path.join(out, "03-report-overview.png") });
await page.getByTestId("tab-findings").click();
await page.getByTestId("panel-findings").waitFor();
const n = await page.getByTestId("finding").count();
res["findings_in_ui"] = n;
await page.screenshot({ path: path.join(out, "04-findings.png") });
const first = page.getByTestId("finding").first();
await first.getByTestId("toggle-details").click();
await first.getByTestId("open-evidence").first().click();
await page.getByTestId("lightbox").waitFor();
await page.locator('[data-testid="lightbox"][data-state="loaded"]').waitFor({ timeout: 20_000 });
await page.getByTestId("region").waitFor({ state: "visible" });
res["screenshot_naturalWidth"] = await page.locator(".shot img").evaluate((i: HTMLImageElement) => i.naturalWidth);
res["screenshot_naturalHeight"] = await page.locator(".shot img").evaluate((i: HTMLImageElement) => i.naturalHeight);
await page.screenshot({ path: path.join(out, "05-evidence-lightbox-region.png") });
res["page_errors"] = errs;
fs.writeFileSync(path.join(out, "ui-submit.json"), JSON.stringify(res, null, 2));
console.log(JSON.stringify(res));
await b.close();
